### PR TITLE
update ruby-stream version

### PR DESCRIPTION
**Pull request by victorfgs**
Updates major version of the `ruby-stream` dependency

### CODE REVIEW

**Review by ferhatelmas — APPROVED** [review]
LGTM

**Comment by ferhatelmas** [comment]
@victorfgs thanks for PR :+1: Are you using it to build anything?

**Comment by victorfgs** [comment]
@ferhatelmas 
We've been using this gem to build part of our notification system @ qulture.rocks

**Comment by ferhatelmas** [comment]
@victorfgs awesome. In the following days, we will give some love here. If you need anything or have ideas to improve, please feel free to open issues. Thanks for contribution and good luck in developing!

**Pull request merged**
